### PR TITLE
Fix for #47

### LINKED ISSUE #47: Fix: Breaking change commited into bot
The newest merge caused issues that stop the code from compiling. Fix the code so that the bot may run without errors.

### PR DESCRIPTION
**Pull request by ankan792**
closes #47

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -66,20 +66,20 @@ func init() { flag.Parse() }
...
+	err := godotenv.Load(".env")
+	if err != nil {
+		log.Fatalf("Error loading .env file")
+		return
+	}
+	//apply env variables to secrets
+	token = os.Getenv("TOKEN")
+	aptly = os.Getenv("API_KEY")
+	logChannelID = os.Getenv("LOG_CHANNEL_ID")
+	botPrefix = os.Getenv("BOTPREFIX")
```
Comment (z404) [inline main.go:79]: Small change, there needs to be an underscore here: `BOT_PREFIX`, as it is specified in that way in the `.env.sample` file.

**Review by z404 — CHANGES_REQUESTED** [review]

**Review by z404 — APPROVED** [review]
Works perfectly, thanks again!

**Comment by ankan792** [comment]
@z404 glad to help!
